{
 "title": "Debezium",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "connector",
    "label": "connector",
    "query": {
     "query": "kafka_connect_connector_task_metrics_running_ratio"
    }
   },
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "debezium_postgres_connector_metrics_totaltablecount"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Total connectors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_count",
     "legendFormat": "task:{{task}}"
    }
   ]
  },
  {
   "title": "Total tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_task_count",
     "legendFormat": "task:{{task}}"
    }
   ]
  },
  {
   "title": "Paused tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_paused_task_count{connector=\"$connector\"}",
     "legendFormat": "task:{{task}}"
    }
   ]
  },
  {
   "title": "Unassigned tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_unassigned_task_count{connector=\"$connector\"}",
     "legendFormat": "task:{{task}}"
    }
   ]
  },
  {
   "title": "Failed tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_failed_task_count{connector=\"$connector\"}",
     "legendFormat": "task:{{task}}"
    }
   ]
  },
  {
   "title": "Streaming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Time since last event",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_millisecondssincelastevent{server=\"$server\", context=\"streaming\"}"
    }
   ]
  },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_connected{server=\"$server\", context=\"streaming\"}"
    }
   ]
  },
  {
   "title": "Total event count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_totalnumberofeventsseen{server=\"$server\", context=\"streaming\"}",
     "legendFormat": "Total events received"
    }
   ]
  },
  {
   "title": "Create event count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_totalnumberofcreateeventsseen{server=\"$server\", context=\"streaming\"}",
     "legendFormat": "Total events received"
    }
   ]
  },
  {
   "title": "Update event count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_totalnumberofupdateeventsseen{server=\"$server\", context=\"streaming\"}",
     "legendFormat": "Total events received"
    }
   ]
  },
  {
   "title": "Delete event count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_totalnumberofdeleteeventsseen{server=\"$server\", context=\"streaming\"}",
     "legendFormat": "Total events received"
    }
   ]
  },
  {
   "title": "Snapshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Total event count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_totalnumberofeventsseen{server=\"$server\", context=\"snapshot\"}",
     "legendFormat": "Total events received"
    }
   ]
  },
  {
   "title": "Table count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_totaltablecount{server=\"$server\", context=\"snapshot\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_snapshotcompleted{server=\"$server\", context=\"snapshot\"}"
    }
   ]
  },
  {
   "title": "Rows scanned",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_rowsscanned{server=\"$server\", context=\"snapshot\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area='heap'}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_bytes_max{area='heap'}",
       "legendFormat": "Maximum"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_threads_current", "legendFormat": "Running" },
      { "expr": "jvm_threads_peak", "legendFormat": "Maximum" },
      { "expr": "jvm_threads_started_total", "legendFormat": "Started in total" }
     ]
    }
   ]
  }
 ]
}